### ISSUE TITLE
Preoprocess Forest mask

### ISSUE THREAD

**Issue by Hannes-Ole** [HAFL-WWI/TBk#63]
### Issue Description:
Forest masks can cause TBk preparation or the core algorithm (clip) to fail. To give unexpierenced users a way of coping with these problems, we can integrate a few common fix/cleanup options in an optional preprocess tool.

### Goal: 
Create a "Preprocess Perimeter" tool, that implements common fix/cleanup options.

- [ ] **repair geometry** (the most basic check, by _default on_)
- [ ] **convert/filter geometry type**, convert all to (multi-)polygons (fixes problems with unsupported/problematic geometry types, e.g. multisurface, by _default on_))
- [ ] [optional] **filter small areas** by default with parameter min_area, e.g. default < 1000 m2 (unclutter the forest mask, e.g. swissTLM3D forests often include small stripes/islands of forests that are irrelevant for TBk | by _default off_)
- [ ] [optional] **buffer dissolve** by paramter buffer_size, e.g. default 0.01 m (this is a simple, dirty but effective way to clear geometry errors, even better than a repair geometry through recreating all geometries, but it also changes the geometries, e.g. merging neighboring/separated regions. Often this is not an issue, particularily for small perimeters, but it makes it likely incompatible with #42; therefore it should be optional | by _default off_).
- [ ] [optional] **cut forest mask** e.g. by using (swissTLM3D) streets or owners vector dataset (as preparation for regionwise processing #42 | by _default off_, only activates when providing cutting layer)

### Motivation:
During processing GR we encountered problems with the cantonal forest mask. Likely the geometry type "multisurface" caused the issues; a buffer (0.01 m) + dissolve solved these problems. The preprocessing tool crashed with a misleading error (sth. along the lines of `gdal_copy compression ZSTD`), suggesting problems with the raster/compression instead of the actual culprit: the forest mask vector.

I had similar problems before with strange geometries, overlaps or other inconsistencies in vector datasets used as perimeter. The (legacy) option "Rasterize Forest Mask" was probably built as a workaround; I'd prefer to fix the geometry, since the forest mask will be used in the TBk generation anyways and there rasterization is not a (good) option.

### Further Remarks:
- [ ] this should be callable by the "main" preprocess tool (#57), e.g. a small boolean checkbox that, when activated, performs the basic/default behavior of "Preprocess perimeter" along with preprocessing VHM/MG. The resulting forest mask is written to the same directory as all the other preprocessed files.
